# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67769810ada85da71d8575936794e0220a68d5faf28523db9e7b5c194796cab65b8435eecf5b66f36407d4159a25be42cf2e4efa5e763ad84690597c571a9874

test:
  secret_key_base: 2b62a8273fd68bea707cbf7c8ee8faa49badfa6cf593d5d850708a83dfbcc72f0893e00c80da4a012444cbeedab89b70a6551aef15010177d62e8770584393d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
